/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlda;

import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.LayoutManager;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.table.DefaultTableModel;

public class QuanLyThuVien extends javax.swing.JFrame {

    DanhSachSach dss = new DanhSachSach();
    DefaultTableModel dtm = new DefaultTableModel();
    GiaoDienMuonSach giaodien = new GiaoDienMuonSach();
    public int n, x;
    public String Tl;
    public QuanLyThuVien() {
        dss.docFile();
        initComponents();
        tblDanhSach.setModel(dtm);
        dtm.setColumnIdentifiers(new Object[]{"Mã Sách", "Tên Sách", "Tác Giả", "Thể Loại", "Ngày SX", "Số Trang"});
        txtMaSach.setEnabled(false);
        txtTenSach.setEnabled(false);
        txtTacGia.setEnabled(false);
        txtSoTrang.setEnabled(false);
        txtNgaySX.setEnabled(false);
        btnLamMoi.setVisible(false);
        btnThem.setVisible(false);
        btnOk.setVisible(false);
        n = dss.a.size();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        rbTinhCam = new javax.swing.JRadioButton();
        rbKinhDi = new javax.swing.JRadioButton();
        rbHanhDong = new javax.swing.JRadioButton();
        rbTuTien = new javax.swing.JRadioButton();
        rbTheLoaiKhac = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTacGia = new javax.swing.JTextField();
        txtTenSach = new javax.swing.JTextField();
        txtNgaySX = new javax.swing.JTextField();
        txtMaSach = new javax.swing.JTextField();
        txtSoTrang = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        lbThemSach = new javax.swing.JLabel();
        btnOk = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDanhSach = new javax.swing.JTable();
        btnThemSach = new javax.swing.JButton();
        btnMuonSach = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lbKho = new javax.swing.JLabel();
        btTatCa = new javax.swing.JButton();
        btnTimSach = new javax.swing.JButton();
        btnDong = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Thư Viện Sách");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        rbTinhCam.setBackground(new java.awt.Color(51, 255, 255));
        buttonGroup1.add(rbTinhCam);
        rbTinhCam.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rbTinhCam.setText("Tình Cảm");
        rbTinhCam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbTinhCamActionPerformed(evt);
            }
        });

        rbKinhDi.setBackground(new java.awt.Color(102, 255, 255));
        buttonGroup1.add(rbKinhDi);
        rbKinhDi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rbKinhDi.setText("Kinh Dị");
        rbKinhDi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbKinhDiActionPerformed(evt);
            }
        });

        rbHanhDong.setBackground(new java.awt.Color(51, 255, 255));
        buttonGroup1.add(rbHanhDong);
        rbHanhDong.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rbHanhDong.setText("Hành Động");
        rbHanhDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbHanhDongActionPerformed(evt);
            }
        });

        rbTuTien.setBackground(new java.awt.Color(51, 255, 255));
        buttonGroup1.add(rbTuTien);
        rbTuTien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rbTuTien.setText("Tu Tiên");
        rbTuTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbTuTienActionPerformed(evt);
            }
        });

        rbTheLoaiKhac.setBackground(new java.awt.Color(51, 255, 255));
        buttonGroup1.add(rbTheLoaiKhac);
        rbTheLoaiKhac.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rbTheLoaiKhac.setText("Thể Loại Khác");
        rbTheLoaiKhac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbTheLoaiKhacActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rbTheLoaiKhac, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbTuTien, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbHanhDong, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbKinhDi, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbTinhCam, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(rbKinhDi, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rbHanhDong, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rbTinhCam, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rbTuTien, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rbTheLoaiKhac, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Mã Sách");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Tên Sách");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Tác Giả");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Ngày SX");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Số Trang");

        txtTacGia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTacGia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTacGiaKeyReleased(evt);
            }
        });

        txtTenSach.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTenSach.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTenSachKeyReleased(evt);
            }
        });

        txtNgaySX.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtNgaySX.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNgaySXKeyReleased(evt);
            }
        });

        txtMaSach.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtMaSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaSachActionPerformed(evt);
            }
        });
        txtMaSach.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMaSachKeyReleased(evt);
            }
        });

        txtSoTrang.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtSoTrang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSoTrangKeyReleased(evt);
            }
        });

        btnThem.setBackground(new java.awt.Color(102, 255, 102));
        btnThem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnLamMoi.setBackground(new java.awt.Color(102, 255, 102));
        btnLamMoi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLamMoi.setText("Làm Mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        lbThemSach.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnOk.setBackground(new java.awt.Color(153, 255, 153));
        btnOk.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnOk.setText("OK ^^");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbThemSach, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btnOk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txtTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNgaySX, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(txtTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNgaySX, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSoTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLamMoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbThemSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        tblDanhSach.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblDanhSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblDanhSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhSachMouseClicked(evt);
            }
        });
        tblDanhSach.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblDanhSachKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblDanhSach);

        btnThemSach.setBackground(new java.awt.Color(255, 255, 0));
        btnThemSach.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnThemSach.setText("Thêm Sách");
        btnThemSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemSachActionPerformed(evt);
            }
        });

        btnMuonSach.setBackground(new java.awt.Color(255, 255, 102));
        btnMuonSach.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnMuonSach.setText("Mượn Sách");
        btnMuonSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMuonSachActionPerformed(evt);
            }
        });

        btnCapNhat.setBackground(new java.awt.Color(255, 255, 102));
        btnCapNhat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCapNhat.setText("Cập Nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(255, 255, 51));
        btnXoa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnXoa.setText("Xoá Sách");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbKho.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbKho.setText("Sách Theo Thể Loại");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(lbKho, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbKho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btTatCa.setText("Xem tất cả");
        btTatCa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTatCaActionPerformed(evt);
            }
        });

        btnTimSach.setBackground(new java.awt.Color(255, 255, 51));
        btnTimSach.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnTimSach.setText("Tìm Sách");
        btnTimSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimSachActionPerformed(evt);
            }
        });

        btnDong.setBackground(new java.awt.Color(255, 255, 51));
        btnDong.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDong.setText("Đóng Thư Viện");
        btnDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDongActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(255, 255, 51));
        btnSua.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSua.setText("Sửa Sách");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btTatCa, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(211, 211, 211)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1062, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnTimSach, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThemSach, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMuonSach, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDong, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btTatCa, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnThemSach, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btnTimSach, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btnMuonSach, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(btnDong, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbKinhDiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbKinhDiActionPerformed
        removeTable();
        int tl = TheLoai();
        lbKho.setText("Sách Theo Thể Loại");
        ArrayList<Sach> ds = dss.timTheLoai(tl);
        for (Sach x : ds) {
            dtm.addRow(new Object[]{x.maSach, x.tenSach, x.tacGia, x.chuyendoi(), x.ngay.toString(), x.soTrang});
        }
        
    }//GEN-LAST:event_rbKinhDiActionPerformed

    private void rbHanhDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbHanhDongActionPerformed
        int tl = TheLoai();
        lbKho.setText("Sách Theo Thể Loại");
        removeTable();
        ArrayList<Sach> ds = new ArrayList<Sach>();
        ds = dss.timTheLoai(tl);
        for (Sach x : ds) {
            dtm.addRow(new Object[]{x.maSach, x.tenSach, x.tacGia, x.chuyendoi(), x.ngay.toString(), x.soTrang});
        }
    }//GEN-LAST:event_rbHanhDongActionPerformed

    private void rbTinhCamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTinhCamActionPerformed
        int tl = TheLoai();
        removeTable();
        lbKho.setText("Sách Theo Thể Loại");
        ArrayList<Sach> ds = new ArrayList<Sach>();
        ds = dss.timTheLoai(tl);
        for (Sach x : ds) {
            dtm.addRow(new Object[]{x.maSach, x.tenSach, x.tacGia, x.chuyendoi(), x.ngay.toString(), x.soTrang});
        }
    }//GEN-LAST:event_rbTinhCamActionPerformed

    private void rbTuTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTuTienActionPerformed
        int tl = TheLoai();
        removeTable();
        lbKho.setText("Sách Theo Thể Loại");
        ArrayList<Sach> ds = new ArrayList<Sach>();
        ds = dss.timTheLoai(tl);
        for (Sach x : ds) {
            dtm.addRow(new Object[]{x.maSach, x.tenSach, x.tacGia, x.chuyendoi(), x.ngay.toString(), x.soTrang});
        }        // TODO add your handling code here:
    }//GEN-LAST:event_rbTuTienActionPerformed

    private void rbTheLoaiKhacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTheLoaiKhacActionPerformed

        removeTable();
        lbKho.setText("Sách Theo Thể Loại");
        int tl = TheLoai();
        ArrayList<Sach> ds = new ArrayList<Sach>();
        ds = dss.timTheLoai(tl);
        for (Sach x : ds) {
            dtm.addRow(new Object[]{x.maSach, x.tenSach, x.tacGia, x.chuyendoi(), x.ngay.toString(), x.soTrang});
        }        // TODO add your handling code here:
    }//GEN-LAST:event_rbTheLoaiKhacActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        int result = JOptionPane.showConfirmDialog(null, "Cập nhật danh sách hiện tại vào kho của thư viện ?", "Xác nhận",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        if (result == JOptionPane.YES_OPTION) {
            dss.capNhat();
            JOptionPane.showMessageDialog(null, "Cập nhật thành công");
        }
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void txtMaSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaSachActionPerformed

    }//GEN-LAST:event_txtMaSachActionPerformed

    private void btnThemSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemSachActionPerformed
        txtMaSach.setEnabled(true);
        txtTenSach.setEnabled(true);
        txtTacGia.setEnabled(true);
        txtSoTrang.setEnabled(true);
        txtNgaySX.setEnabled(true);
        btnThem.setVisible(true);
        btnLamMoi.setVisible(true);
        btnLamMoi.setEnabled(false);
        btnThem.setEnabled(false);
        txtMaSach.requestFocus();
          btnOk.setVisible(false);
          txtMaSach.setText("");
        txtTenSach.setText("");
        txtTacGia.setText("");
        txtSoTrang.setText("");
        txtNgaySX.setText("");
        btnLamMoi.setEnabled(false);
        txtMaSach.requestFocus();

    }//GEN-LAST:event_btnThemSachActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        txtMaSach.setText("");
        txtTenSach.setText("");
        txtTacGia.setText("");
        txtSoTrang.setText("");
        txtNgaySX.setText("");
        btnLamMoi.setEnabled(false);
        txtMaSach.requestFocus();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void txtMaSachKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaSachKeyReleased
        btnLamMoi.setEnabled(true);
    }//GEN-LAST:event_txtMaSachKeyReleased

    private void txtTenSachKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTenSachKeyReleased
        btnLamMoi.setEnabled(true);
    }//GEN-LAST:event_txtTenSachKeyReleased

    private void txtTacGiaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTacGiaKeyReleased
        btnLamMoi.setEnabled(true);
    }//GEN-LAST:event_txtTacGiaKeyReleased

    private void txtNgaySXKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNgaySXKeyReleased
        btnLamMoi.setEnabled(true);
    }//GEN-LAST:event_txtNgaySXKeyReleased

    private void txtSoTrangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSoTrangKeyReleased
        btnLamMoi.setEnabled(true);
        if (isOK()) {
            btnThem.setEnabled(true);
        }
    }//GEN-LAST:event_txtSoTrangKeyReleased

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        
        if (isOK()) {
            String ma = txtMaSach.getText();
            String ten = txtTenSach.getText();
            String tg = txtTacGia.getText();
            String ngay = txtNgaySX.getText();
            int soTrang = Integer.parseInt(txtSoTrang.getText());
            int theloai = TheLoai();
            if (theloai == -1) {
                JOptionPane.showMessageDialog(null, "Vui Lòng  lựa chọn thể loại trong danh sách");
                return;

            }
            if (dss.TimKiemMa(ma) != null) {
                JOptionPane.showMessageDialog(null, "Mã sách đã tồn tại, Vui lòng nhập lại mã sách mới");
                txtMaSach.requestFocus();
                return;
            }
            if (dss.timTheoTen(ten) != null) {
                JOptionPane.showMessageDialog(null, "Tên sách đã tồn tại, Vui lòng nhập lại tên mới cho sách");
                txtTenSach.requestFocus();
                return;
            }
            int result = JOptionPane.showConfirmDialog(null,
                    "Bạn muốn thêm sách vào thư viện: ",
                    "Xác nhận",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE);
            if (result == JOptionPane.YES_OPTION) {
                dss.themSach(ma, ten, ngay, tg, theloai, soTrang);
                dtm.addRow(new Object[]{ma, ten, tg, dss.a.get(dss.a.size() - 1).chuyendoi(), ngay, soTrang});
                txtMaSach.setText("");
                txtTenSach.setText("");
                txtTacGia.setText("");
                txtSoTrang.setText("");
                txtNgaySX.setText("");
                btnLamMoi.setEnabled(false);
                txtMaSach.requestFocus();
                lbThemSach.setText("Thêm thành công");
            }

        } else {
            txtMaSach.requestFocus();
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
   btnOk.setVisible(false);
        removeTable();
        lbKho.setText("Sách Thư Viện");
        rbTinhCam.setSelected(false);
        rbHanhDong.setSelected(false);
        rbKinhDi.setSelected(false);
        rbTuTien.setSelected(false);
        rbTheLoaiKhac.setSelected(false);
        for (int i = 0; i < dss.a.size(); i++) {
            dtm.addRow(new Object[]{dss.a.get(i).maSach, dss.a.get(i).tenSach, dss.a.get(i).tacGia, dss.a.get(i).chuyendoi(), dss.a.get(i).ngay.toString(), dss.a.get(i).soTrang});
        }
        String ma = JOptionPane.showInputDialog(null, "Nhập mã sách cần xoá: ");
        if (dss.TimKiemMa(ma.trim()) != null) {
            int result = JOptionPane.showConfirmDialog(null, "Xác nhận xoá sách có mã " + ma.toUpperCase(), "Xác nhận",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE);
            if (result == JOptionPane.YES_OPTION) {
                if (dss.xoaSachTheoMa(ma) == true) {
                    JOptionPane.showMessageDialog(null, "Xoá thành công");
                    removeTable();
                    for (int i = 0; i < dss.a.size(); i++) {
                        dtm.addRow(new Object[]{dss.a.get(i).maSach, dss.a.get(i).tenSach, dss.a.get(i).tacGia, dss.a.get(i).chuyendoi(), dss.a.get(i).ngay.toString(), dss.a.get(i).soTrang});
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Xoá thất bại");
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Không tìm thấy mã sách cần xoá");
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnMuonSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMuonSachActionPerformed
          btnOk.setVisible(false);
        if (dss.a.size() != n) {
            int result = JOptionPane.showConfirmDialog(null, "Lưu thay đổi sách mới vào kho", "Xác nhận", JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE);
            if (result == JOptionPane.YES_NO_OPTION) {
                dss.capNhat();
            }
        }
        giaodien.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        giaodien.setLocationByPlatform(true);
        giaodien.setSize(1250, 700);
        giaodien.setVisible(true);
        giaodien.setDefaultCloseOperation(0);
        giaodien.setFocusable(true);
        giaodien.dss.docFile();
    }//GEN-LAST:event_btnMuonSachActionPerformed

    private void btTatCaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTatCaActionPerformed
        removeTable();
        lbKho.setText("Sách Thư Viện");
        rbTinhCam.setSelected(false);
        rbHanhDong.setSelected(false);
        rbKinhDi.setSelected(false);
        rbTuTien.setSelected(false);
        rbTheLoaiKhac.setSelected(false);
        for (int i = 0; i < dss.a.size(); i++) {
            dtm.addRow(new Object[]{dss.a.get(i).maSach, dss.a.get(i).tenSach, dss.a.get(i).tacGia, dss.a.get(i).chuyendoi(), dss.a.get(i).ngay.toString(), dss.a.get(i).soTrang});
        }
    }//GEN-LAST:event_btTatCaActionPerformed

    private void btnTimSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimSachActionPerformed
           btnOk.setVisible(false);
        String ma = JOptionPane.showInputDialog(null, "Nhập mã sách cần tìm kiếm: ");
        if (dss.TimKiemMa(ma.trim()) != null) {
            removeTable();
            lbKho.setText("Sách cần tìm");
            Sach sach = dss.TimKiemMa(ma.trim());
            dtm.addRow(new Object[]{sach.maSach, sach.tenSach, sach.tacGia, sach.chuyendoi(), sach.ngay, sach.soTrang});
        } else {
            JOptionPane.showMessageDialog(null, "Không tìm thấy mã " + ma + " trong Thư Viện");
        }
    }//GEN-LAST:event_btnTimSachActionPerformed

    private void btnDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDongActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnDongActionPerformed

    private void tblDanhSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachMouseClicked
        x = tblDanhSach.getSelectedRow();
        displayDetails(x);
        Tl = dtm.getValueAt(x, 3).toString();
    }//GEN-LAST:event_tblDanhSachMouseClicked
    
    public void displayDetails(int g) {
        txtMaSach.setText(dtm.getValueAt(g, 0).toString());
        txtTenSach.setText(dtm.getValueAt(g, 1).toString());
        txtTacGia.setText(dtm.getValueAt(g, 2).toString());
        txtNgaySX.setText(dtm.getValueAt(g, 4).toString());
        txtSoTrang.setText(dtm.getValueAt(g, 5).toString());
    }
    private void tblDanhSachKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblDanhSachKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tblDanhSachKeyReleased

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        btnOk.setVisible(true);
        txtMaSach.setEnabled(true);
        txtTenSach.setEnabled(true);
        txtTacGia.setEnabled(true);
        txtNgaySX.setEnabled(true);
        txtSoTrang.setEnabled(true);
        JOptionPane.showMessageDialog(null, "Vui lòng chọn một sách cần sửa trong bảng");
        for (int i = 0; i < dss.a.size(); i++) {
            dtm.addRow(new Object[]{dss.a.get(i).maSach, dss.a.get(i).tenSach, dss.a.get(i).tacGia, dss.a.get(i).chuyendoi(), dss.a.get(i).ngay.toString(), dss.a.get(i).soTrang});
        }
        return;
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        
        String ma = txtMaSach.getText();
         String ten = txtTenSach.getText();
        String tg = txtTacGia.getText();
        String ngay = txtNgaySX.getText();
        int soTrang = Integer.parseInt(txtSoTrang.getText());
        int theloai = DaoNguoc(Tl);
        dss.a.get(x).setMaSach(ma);
        dss.a.get(x).setTenSach(ten);
        dss.a.get(x).setTacGia(tg);
        dss.a.get(x).setNgay(new NgayThang(ngay));
        dss.a.get(x).setSoTrang(soTrang);
        dss.a.get(x).setTheloai(theloai);
        removeTable();
         for (int i = 0; i < dss.a.size(); i++) {
            dtm.addRow(new Object[]{dss.a.get(i).maSach, dss.a.get(i).tenSach, dss.a.get(i).tacGia, dss.a.get(i).chuyendoi(), dss.a.get(i).ngay.toString(), dss.a.get(i).soTrang});
        }
    }//GEN-LAST:event_btnOkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyThuVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyThuVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyThuVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyThuVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyThuVien().setVisible(true);
            }
        });
    }

    public void removeTable() {
        dtm.setRowCount(0);
    }
    public int DaoNguoc(String loai){
        if(loai.trim().compareToIgnoreCase("Kinh Di")==0) return 1;
        if(loai.trim().compareToIgnoreCase("Tinh Cam")==0) return 2;
        if(loai.trim().compareToIgnoreCase("Hanh Dong")==0) return 3;
        if(loai.trim().compareToIgnoreCase("Tu tien")==0) return 1;
        if(loai.trim().compareToIgnoreCase("The Loai Khac")==0) return 0;
        return -1;
        
    }
    public int TheLoai() {
        if (rbKinhDi.isSelected()) {
            return 1;
        }
        if (rbTinhCam.isSelected()) {
            return 2;
        }
        if (rbTuTien.isSelected()) {
            return 4;
        }
        if (rbHanhDong.isSelected()) {
            return 3;
        }
        if (rbTheLoaiKhac.isSelected()) {
            return 0;
        }
        return -1;
    }

    public boolean isOK() {
        if (txtMaSach.getText().equals("")) {
            return false;
        }
        if (txtTenSach.getText().equals("")) {
            return false;
        }
        if (txtTacGia.getText().equals("")) {
            return false;
        }
        if (txtNgaySX.getText().equals("")) {
            return false;
        }
        if (txtSoTrang.getText().equals("")) {
            return false;
        }
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btTatCa;
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnDong;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnMuonSach;
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThemSach;
    private javax.swing.JButton btnTimSach;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbKho;
    private javax.swing.JLabel lbThemSach;
    private javax.swing.JRadioButton rbHanhDong;
    private javax.swing.JRadioButton rbKinhDi;
    private javax.swing.JRadioButton rbTheLoaiKhac;
    private javax.swing.JRadioButton rbTinhCam;
    private javax.swing.JRadioButton rbTuTien;
    private javax.swing.JTable tblDanhSach;
    private javax.swing.JTextField txtMaSach;
    private javax.swing.JTextField txtNgaySX;
    private javax.swing.JTextField txtSoTrang;
    private javax.swing.JTextField txtTacGia;
    private javax.swing.JTextField txtTenSach;
    // End of variables declaration//GEN-END:variables
}
